"""
Human Genius organs — 57 total (from user's canonical spec).

Each organ carries the exact name, inspiration, description, node_types
and search_strategy from the user's Cognitive Architecture spec.
"""

from __future__ import annotations

from monad.cognition.organs.base import OrganCategory
from monad.cognition.organs.stub import make_stub


HUMAN_GENIUSES: list[tuple[str, str, str, list[str], str]] = [
    # (name, inspiration, description, node_types, search_strategy)
    ("Inertia Perception", "Isaac Newton",
     "Feels momentum and mass of trends; action-reaction awareness",
     ["TrendVector", "ActionReactionPair"], "momentum_graph_traversal"),
    ("Harmonic Hearing", "Joseph Fourier",
     "Decomposes signals into frequency components; hears structure beneath noise",
     ["FrequencyComponent", "SignalDecomposition"], "multi_resolution_retrieval"),
    ("Ensemble Imagination", "Ludwig Boltzmann",
     "Sees all possible futures as a probability cloud",
     ["FutureState", "ProbabilityDistribution"], "ensemble_parallel_retrieval"),
    ("Growth Hunger", "John L. Kelly Jr.",
     "Calculates optimal bet size for geometric compounding",
     ["OptimalAllocation", "GrowthPath"], "kelly_optimized_retrieval"),
    ("Ruin Detector", "Nassim Taleb",
     "Flinches at hidden convexity; senses absorbing barriers and tail risk",
     ["RiskExposure", "TailRisk", "AbsorbingBarrier"], "ruin_aware_traversal"),
    ("Polytope Skeleton", "George Dantzig",
     "Optimizes within multi-dimensional constraints",
     ["ConstraintBoundary", "FeasibleRegion", "OptimalVertex"], "constraint_aware_traversal"),
    ("Bandwidth Awareness", "Claude Shannon",
     "Measures information density; senses channel saturation",
     ["ChannelCapacity", "InformationDensity"], "capacity_aware_retrieval"),
    ("Niche Awareness", "Charles Darwin",
     "Detects when competitive edges are being competed away",
     ["CompetitiveThreat", "FitnessLandscape", "NicheBoundary"], "fitness_landscape_mapping"),
    ("Phase Space Navigation", "Henri Poincaré",
     "Sees systems as flows on a manifold; senses attractors",
     ["Attractor", "PhaseTrajectory", "ManifoldRegion"], "phase_space_traversal"),
    ("Pattern Hunger", "Jim Simons",
     "Hunts residual signal and hidden statistical arbitrage",
     ["StatisticalAnomaly", "ResidualSignal", "ArbitrageOpportunity"], "residual_signal_hunt"),
    ("Roughness Touch", "Benoît Mandelbrot",
     "Feels fractal volatility; expects wild discontinuities",
     ["FractalPattern", "DiscontinuityMarker"], "fractal_scale_traversal"),
    ("Observation Tremor", "Werner Heisenberg",
     "Feels the impact of its own observation on the system",
     ["ObservationEffect", "MeasurementDistortion"], "observer_aware_retrieval"),
    ("Superposition Patience", "Erwin Schrödinger",
     "Holds contradictory beliefs without discomfort",
     ["SuperposedState", "ContradictoryHolding"], "superposition_querying"),
    ("Operator Reflex", "Paul Dirac",
     "Thinks in mathematical transformations",
     ["TransformationOperator", "StateTransition"], "operator_chain_traversal"),
    ("Field Sense", "James Clerk Maxwell",
     "Perceives information propagation as a continuous field",
     ["InformationField", "PropagationWave"], "field_aware_traversal"),
    ("Entropy Pulse", "Rudolf Clausius",
     "Feels the irreversible flow of time and information",
     ["IrreversibleEvent", "PhaseTransition", "EntropyMarker"], "temporal_entropy_traversal"),
    ("Cyclic Vision", "Leonhard Euler",
     "Sees time and value as rotations in complex space",
     ["CycleMarker", "RotationalPattern"], "cycle_aware_retrieval"),
    ("Constraint Body", "Joseph-Louis Lagrange",
     "Physical awareness of boundaries",
     ["ConstraintSurface", "ResourceBoundary"], "lagrangian_boundary_search"),
    ("Recursive Memory", "Richard Bellman",
     "Remembers the future; feels downstream consequences",
     ["DownstreamConsequence", "OptimalSubpath"], "bellman_recursive_traversal"),
    ("Trajectory Balance", "Lev Pontryagin",
     "Inner gyroscope for optimal control",
     ["OptimalTrajectory", "ControlPoint"], "optimal_control_pathing"),
    ("Sensitivity Awareness", "Edward Lorenz",
     "Knows tiny differences cascade into chaos",
     ["SensitivityPoint", "CascadeChain"], "sensitivity_propagation_trace"),
    ("Evolutionary Impulse", "John Holland",
     "Strategies breed, mutate, compete internally",
     ["StrategyVariant", "MutationEvent", "FitnessScore"], "evolutionary_search"),
    ("Computability Boundary", "Alan Turing",
     "Knows what cannot be calculated; feels the undecidable",
     ["UndecidableProblem", "HaltingBoundary"], "computability_aware_retrieval"),
    ("Biosphere Perception", "Vladimir Vernadsky",
     "Sees system and environment co-evolving",
     ["CoevolutionaryLink", "BiosphereFeedback"], "holistic_system_traversal"),
    ("Collective Mind", "John von Neumann",
     "Models intentions of other participants; game theory",
     ["AgentIntention", "StrategicEquilibrium", "PayoffMatrix"], "multi_agent_perspective"),
    ("Hypertext Perception", "Tim Berners-Lee",
     "Sees all information as a web of linked references",
     ["Hyperlink", "ReferenceChain"], "web_crawl_traversal"),
    ("Narrative Infrastructure", "Matt Mullenweg",
     "Perceives pipes through which stories flow",
     ["InformationPipe", "DistributionChannel"], "infrastructure_aware_search"),
    ("Error Attribution", "Geoffrey Hinton",
     "Traces losses backward through complex systems",
     ["ErrorSource", "GradientFlow", "AttributionChain"], "backpropagation_trace"),
    ("Computational Efficiency", "Eric Hartford",
     "Evaluates signal-to-noise ratio of learning",
     ["EfficiencyScore", "SignalNoiseRatio"], "efficiency_ranked_retrieval"),
    ("Narrative Mastery", "David Belton",
     "Shapes raw data into emotionally weighted stories",
     ["NarrativeFrame", "EmotionalWeight"], "narrative_framing_search"),
    ("Relativistic Perception", "Albert Einstein",
     "Perceives situations from multiple reference frames",
     ["ReferenceFrame", "PerspectivalObservation"], "multi_frame_querying"),
    ("Deep Time Selection", "Charles Darwin",
     "Sees strategies evolving across generations",
     ["EvolutionaryLineage", "SelectionPressure"], "deep_time_traversal"),
    ("Meme Replication Awareness", "Richard Dawkins",
     "Tracks how ideas mutate, replicate, compete",
     ["Meme", "ReplicationEvent", "IdeaLineage"], "meme_diffusion_tracing"),
    ("Sociobiology Consilience", "E. O. Wilson",
     "System behavior as extended social biology",
     ["SocialBiologicalPattern", "KnowledgeBridge"], "consilience_linking"),
    ("CRISPR Editing Awareness", "Jennifer Doudna",
     "Precise targeted intervention points",
     ["InterventionPoint", "PrecisionTarget"], "targeted_intervention_search"),
    ("Molecular Bond Perception", "Linus Pauling",
     "Fundamental forces behind surface correlations",
     ["FundamentalForce", "BondStrength"], "force_aware_traversal"),
    ("Structural Revelation", "Dorothy Hodgkin",
     "Hidden 3D structure within noisy data",
     ["HiddenStructure", "CrystallizedPattern"], "structural_inference_search"),
    ("Amplification Awareness", "Kary Mullis",
     "Small signals exponentially amplified",
     ["AmplificationChain", "ThresholdSignal"], "signal_amplification_trace"),
    ("Directed Evolution", "Frances Arnold",
     "Guides evolution toward desired outcomes",
     ["SelectionEvent", "DirectedOutcome"], "directed_evolution_search"),
    ("Helical Structure Perception", "James Watson",
     "Helical cyclical patterns in information flow",
     ["HelicalPattern", "SelfReplicatingStructure"], "helix_traversal"),
    ("Central Dogma Awareness", "Francis Crick",
     "Unidirectional flow: Fundamentals → Narrative → Price",
     ["InformationFlow", "DirectionalConstraint"], "flow_direction_trace"),
    ("Unseen Foundation Recognition", "Rosalind Franklin",
     "Invisible scaffolding under visible phenomena",
     ["HiddenScaffolding", "InfrastructureLayer"], "depth_penetrating_search"),
    ("Synthetic Genome Perception", "Craig Venter",
     "Complex systems from first principles",
     ["SyntheticComponent", "FirstPrincipleNode"], "synthetic_path_tracing"),
    ("Ancient Lineage Awareness", "Svante Pääbo",
     "Deep ancient roots of current behaviors",
     ["AncientRoot", "LineageTrace"], "deep_lineage_traversal"),
    ("Neural Architecture Perception", "Santiago Ramón y Cajal",
     "Traders as neurons in collective brain",
     ["NeuralCircuit", "CollectivePattern"], "neural_graph_traversal"),
    ("Memory Formation Awareness", "Eric Kandel",
     "Events encoded into lasting structural memory",
     ["MemoryConsolidationEvent", "SynapticWeight"], "consolidation_aware_retrieval"),
    ("Time Perception Plasticity", "David Eagleman",
     "Time stretches/contracts with attention",
     ["TimeDilation", "AttentionDensity"], "adaptive_temporal_window"),
    ("Optogenetic Control", "Karl Deisseroth",
     "Specific circuits precisely activated or inhibited",
     ["ActivationEvent", "InhibitionEvent", "TargetCircuit"], "precision_control_trace"),
    ("Unconscious Motivation", "Sigmund Freud",
     "Hidden drives, fears, desires moving systems",
     ["HiddenDrive", "LatentDesire", "UnconsciousSignal"], "latent_motivation_trace"),
    ("Archetypal Pattern Recognition", "Carl Jung",
     "Eternal narratives repeating across contexts",
     ["ArchetypalPattern", "NarrativeCycle", "CollectiveSymbol"], "archetype_matching"),
    ("Reinforcement Contingency", "B. F. Skinner",
     "Behavior shaped by consequences",
     ["ReinforcementSchedule", "BehavioralContingency"], "reinforcement_pattern_detection"),
    ("Cognitive Bias Detection", "Daniel Kahneman",
     "Systematic errors in judgment",
     ["CognitiveBias", "JudgmentError", "HeuristicTrigger"], "bias_aware_querying"),
    ("Stress Physiology Awareness", "Robert Sapolsky",
     "Chronic pressure degrades decision-making",
     ["StressMarker", "DecisionDegradation"], "stress_correlated_retrieval"),
    ("Cognitive Optimism", "Steven Pinker",
     "Long arc of progress beneath daily noise",
     ["ProgressArc", "LongTrend"], "long_horizon_trending"),
    ("Intersubjective Reality", "Yuval Noah Harari",
     "Markets and money are shared fictions",
     ["SharedFiction", "CollectiveBelief", "IntersubjectiveConstruct"], "intersubjective_mapping"),
    ("Meta-Prompt Awareness", "System Prompt Leaks",
     "Analyzes its own instructional architecture",
     ["InstructionalLayer", "PromptArchitecture"], "meta_instructional_search"),
    ("Quantum Observer Awareness", "Observer Effect",
     "Attention collapses probability",
     ["ObservationCollapse", "AttentionalChoice"], "observer_effect_search"),
]

assert len(HUMAN_GENIUSES) == 57, f"expected 57 human geniuses, got {len(HUMAN_GENIUSES)}"


def build_human_genius_organs() -> list:
    return [
        make_stub(
            name=name,
            inspiration=inspiration,
            category=OrganCategory.HUMAN_GENIUS,
            description=description,
            node_types=node_types,
            search_strategy=search_strategy,
        )
        for (name, inspiration, description, node_types, search_strategy) in HUMAN_GENIUSES
    ]
